/*
 * avoindata-api
 *
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingrid.Client.OpenAPIDateConverter;

namespace Fingrid.Model
{
    /// <summary>
    /// Defines DatasetFormat
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DatasetFormat
    {
        /// <summary>
        /// Enum Csv for value: csv
        /// </summary>
        [EnumMember(Value = "csv")]
        Csv = 1,

        /// <summary>
        /// Enum Json for value: json
        /// </summary>
        [EnumMember(Value = "json")]
        Json = 2,

        /// <summary>
        /// Enum App for value: app
        /// </summary>
        [EnumMember(Value = "app")]
        App = 3,

        /// <summary>
        /// Enum _7zip for value: 7zip
        /// </summary>
        [EnumMember(Value = "7zip")]
        _7zip = 4,

        /// <summary>
        /// Enum Zip for value: zip
        /// </summary>
        [EnumMember(Value = "zip")]
        Zip = 5,

        /// <summary>
        /// Enum Xml for value: xml
        /// </summary>
        [EnumMember(Value = "xml")]
        Xml = 6

    }

}
