/*
 * avoindata-api
 *
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingrid.Client.OpenAPIDateConverter;

namespace Fingrid.Model
{
    /// <summary>
    /// DatasetSearchResultAllOf
    /// </summary>
    [DataContract(Name = "DatasetSearchResult_allOf")]
    public partial class DatasetSearchResultAllOf : IEquatable<DatasetSearchResultAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetSearchResultAllOf" /> class.
        /// </summary>
        /// <param name="searchScore">searchScore.</param>
        public DatasetSearchResultAllOf(double searchScore = default(double))
        {
            this.SearchScore = searchScore;
        }

        /// <summary>
        /// Gets or Sets SearchScore
        /// </summary>
        [DataMember(Name = "searchScore", EmitDefaultValue = false)]
        public double SearchScore { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DatasetSearchResultAllOf {\n");
            sb.Append("  SearchScore: ").Append(SearchScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DatasetSearchResultAllOf);
        }

        /// <summary>
        /// Returns true if DatasetSearchResultAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of DatasetSearchResultAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DatasetSearchResultAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SearchScore == input.SearchScore ||
                    this.SearchScore.Equals(input.SearchScore)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SearchScore.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
