/*
 * avoindata-api
 *
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingrid.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Fingrid.Model
{
    /// <summary>
    /// GetDatasetShorts200Response
    /// </summary>
    [JsonConverter(typeof(GetDatasetShorts200ResponseJsonConverter))]
    [DataContract(Name = "GetDatasetShorts_200_response")]
    public partial class GetDatasetShorts200Response : AbstractOpenAPISchema, IEquatable<GetDatasetShorts200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDatasetShorts200Response" /> class
        /// with the <see cref="IWithPaginationDatasetSearchResult" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IWithPaginationDatasetSearchResult.</param>
        public GetDatasetShorts200Response(IWithPaginationDatasetSearchResult actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDatasetShorts200Response" /> class
        /// with the <see cref="IWithPaginationDatasetShort" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IWithPaginationDatasetShort.</param>
        public GetDatasetShorts200Response(IWithPaginationDatasetShort actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(IWithPaginationDatasetSearchResult))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(IWithPaginationDatasetShort))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: IWithPaginationDatasetSearchResult, IWithPaginationDatasetShort");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `IWithPaginationDatasetSearchResult`. If the actual instance is not `IWithPaginationDatasetSearchResult`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IWithPaginationDatasetSearchResult</returns>
        public IWithPaginationDatasetSearchResult GetIWithPaginationDatasetSearchResult()
        {
            return (IWithPaginationDatasetSearchResult)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `IWithPaginationDatasetShort`. If the actual instance is not `IWithPaginationDatasetShort`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IWithPaginationDatasetShort</returns>
        public IWithPaginationDatasetShort GetIWithPaginationDatasetShort()
        {
            return (IWithPaginationDatasetShort)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetDatasetShorts200Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, GetDatasetShorts200Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of GetDatasetShorts200Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of GetDatasetShorts200Response</returns>
        public static GetDatasetShorts200Response FromJson(string jsonString)
        {
            GetDatasetShorts200Response newGetDatasetShorts200Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newGetDatasetShorts200Response;
            }

            try
            {
                newGetDatasetShorts200Response = new GetDatasetShorts200Response(JsonConvert.DeserializeObject<IWithPaginationDatasetSearchResult>(jsonString, GetDatasetShorts200Response.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newGetDatasetShorts200Response;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IWithPaginationDatasetSearchResult: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newGetDatasetShorts200Response = new GetDatasetShorts200Response(JsonConvert.DeserializeObject<IWithPaginationDatasetShort>(jsonString, GetDatasetShorts200Response.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newGetDatasetShorts200Response;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IWithPaginationDatasetShort: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetDatasetShorts200Response);
        }

        /// <summary>
        /// Returns true if GetDatasetShorts200Response instances are equal
        /// </summary>
        /// <param name="input">Instance of GetDatasetShorts200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetDatasetShorts200Response input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for GetDatasetShorts200Response
    /// </summary>
    public class GetDatasetShorts200ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(GetDatasetShorts200Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return GetDatasetShorts200Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
