/*
 * avoindata-api
 *
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingrid.Client.OpenAPIDateConverter;

namespace Fingrid.Model
{
    /// <summary>
    /// MonitoringResult
    /// </summary>
    [DataContract(Name = "MonitoringResult")]
    public partial class MonitoringResult : IEquatable<MonitoringResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MonitoringResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringResult" /> class.
        /// </summary>
        /// <param name="aisErrors">aisErrors (required).</param>
        /// <param name="timeseries">timeseries (required).</param>
        public MonitoringResult(List<MonitoringAisErrorResult> aisErrors = default(List<MonitoringAisErrorResult>), List<MonitoringTimeseriesResult> timeseries = default(List<MonitoringTimeseriesResult>))
        {
            // to ensure "aisErrors" is required (not null)
            if (aisErrors == null)
            {
                throw new ArgumentNullException("aisErrors is a required property for MonitoringResult and cannot be null");
            }
            this.AisErrors = aisErrors;
            // to ensure "timeseries" is required (not null)
            if (timeseries == null)
            {
                throw new ArgumentNullException("timeseries is a required property for MonitoringResult and cannot be null");
            }
            this.Timeseries = timeseries;
        }

        /// <summary>
        /// Gets or Sets AisErrors
        /// </summary>
        [DataMember(Name = "aisErrors", IsRequired = true, EmitDefaultValue = true)]
        public List<MonitoringAisErrorResult> AisErrors { get; set; }

        /// <summary>
        /// Gets or Sets Timeseries
        /// </summary>
        [DataMember(Name = "timeseries", IsRequired = true, EmitDefaultValue = true)]
        public List<MonitoringTimeseriesResult> Timeseries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MonitoringResult {\n");
            sb.Append("  AisErrors: ").Append(AisErrors).Append("\n");
            sb.Append("  Timeseries: ").Append(Timeseries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MonitoringResult);
        }

        /// <summary>
        /// Returns true if MonitoringResult instances are equal
        /// </summary>
        /// <param name="input">Instance of MonitoringResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MonitoringResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AisErrors == input.AisErrors ||
                    this.AisErrors != null &&
                    input.AisErrors != null &&
                    this.AisErrors.SequenceEqual(input.AisErrors)
                ) && 
                (
                    this.Timeseries == input.Timeseries ||
                    this.Timeseries != null &&
                    input.Timeseries != null &&
                    this.Timeseries.SequenceEqual(input.Timeseries)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AisErrors != null)
                {
                    hashCode = (hashCode * 59) + this.AisErrors.GetHashCode();
                }
                if (this.Timeseries != null)
                {
                    hashCode = (hashCode * 59) + this.Timeseries.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
