/*
 * avoindata-api
 *
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingrid.Client.OpenAPIDateConverter;

namespace Fingrid.Model
{
    /// <summary>
    /// From T, pick a set of properties whose keys are in the union K
    /// </summary>
    [DataContract(Name = "Omit_Notification.id-or-modifiedAtUtc_")]
    public partial class OmitNotificationIdOrModifiedAtUtc : IEquatable<OmitNotificationIdOrModifiedAtUtc>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OmitNotificationIdOrModifiedAtUtc" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OmitNotificationIdOrModifiedAtUtc() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OmitNotificationIdOrModifiedAtUtc" /> class.
        /// </summary>
        /// <param name="messageFi">messageFi (required).</param>
        /// <param name="messageEn">messageEn (required).</param>
        /// <param name="startTimeUtc">startTimeUtc (required).</param>
        /// <param name="endTimeUtc">endTimeUtc (required).</param>
        /// <param name="linkFi">linkFi.</param>
        /// <param name="linkEn">linkEn.</param>
        /// <param name="linkTextFi">linkTextFi.</param>
        /// <param name="linkTextEn">linkTextEn.</param>
        public OmitNotificationIdOrModifiedAtUtc(string messageFi = default(string), string messageEn = default(string), DateTime startTimeUtc = default(DateTime), DateTime endTimeUtc = default(DateTime), string linkFi = default(string), string linkEn = default(string), string linkTextFi = default(string), string linkTextEn = default(string))
        {
            // to ensure "messageFi" is required (not null)
            if (messageFi == null)
            {
                throw new ArgumentNullException("messageFi is a required property for OmitNotificationIdOrModifiedAtUtc and cannot be null");
            }
            this.MessageFi = messageFi;
            // to ensure "messageEn" is required (not null)
            if (messageEn == null)
            {
                throw new ArgumentNullException("messageEn is a required property for OmitNotificationIdOrModifiedAtUtc and cannot be null");
            }
            this.MessageEn = messageEn;
            this.StartTimeUtc = startTimeUtc;
            this.EndTimeUtc = endTimeUtc;
            this.LinkFi = linkFi;
            this.LinkEn = linkEn;
            this.LinkTextFi = linkTextFi;
            this.LinkTextEn = linkTextEn;
        }

        /// <summary>
        /// Gets or Sets MessageFi
        /// </summary>
        [DataMember(Name = "messageFi", IsRequired = true, EmitDefaultValue = true)]
        public string MessageFi { get; set; }

        /// <summary>
        /// Gets or Sets MessageEn
        /// </summary>
        [DataMember(Name = "messageEn", IsRequired = true, EmitDefaultValue = true)]
        public string MessageEn { get; set; }

        /// <summary>
        /// Gets or Sets StartTimeUtc
        /// </summary>
        [DataMember(Name = "startTimeUtc", IsRequired = true, EmitDefaultValue = true)]
        public DateTime StartTimeUtc { get; set; }

        /// <summary>
        /// Gets or Sets EndTimeUtc
        /// </summary>
        [DataMember(Name = "endTimeUtc", IsRequired = true, EmitDefaultValue = true)]
        public DateTime EndTimeUtc { get; set; }

        /// <summary>
        /// Gets or Sets LinkFi
        /// </summary>
        [DataMember(Name = "linkFi", EmitDefaultValue = false)]
        public string LinkFi { get; set; }

        /// <summary>
        /// Gets or Sets LinkEn
        /// </summary>
        [DataMember(Name = "linkEn", EmitDefaultValue = false)]
        public string LinkEn { get; set; }

        /// <summary>
        /// Gets or Sets LinkTextFi
        /// </summary>
        [DataMember(Name = "linkTextFi", EmitDefaultValue = false)]
        public string LinkTextFi { get; set; }

        /// <summary>
        /// Gets or Sets LinkTextEn
        /// </summary>
        [DataMember(Name = "linkTextEn", EmitDefaultValue = false)]
        public string LinkTextEn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OmitNotificationIdOrModifiedAtUtc {\n");
            sb.Append("  MessageFi: ").Append(MessageFi).Append("\n");
            sb.Append("  MessageEn: ").Append(MessageEn).Append("\n");
            sb.Append("  StartTimeUtc: ").Append(StartTimeUtc).Append("\n");
            sb.Append("  EndTimeUtc: ").Append(EndTimeUtc).Append("\n");
            sb.Append("  LinkFi: ").Append(LinkFi).Append("\n");
            sb.Append("  LinkEn: ").Append(LinkEn).Append("\n");
            sb.Append("  LinkTextFi: ").Append(LinkTextFi).Append("\n");
            sb.Append("  LinkTextEn: ").Append(LinkTextEn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OmitNotificationIdOrModifiedAtUtc);
        }

        /// <summary>
        /// Returns true if OmitNotificationIdOrModifiedAtUtc instances are equal
        /// </summary>
        /// <param name="input">Instance of OmitNotificationIdOrModifiedAtUtc to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OmitNotificationIdOrModifiedAtUtc input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MessageFi == input.MessageFi ||
                    (this.MessageFi != null &&
                    this.MessageFi.Equals(input.MessageFi))
                ) && 
                (
                    this.MessageEn == input.MessageEn ||
                    (this.MessageEn != null &&
                    this.MessageEn.Equals(input.MessageEn))
                ) && 
                (
                    this.StartTimeUtc == input.StartTimeUtc ||
                    (this.StartTimeUtc != null &&
                    this.StartTimeUtc.Equals(input.StartTimeUtc))
                ) && 
                (
                    this.EndTimeUtc == input.EndTimeUtc ||
                    (this.EndTimeUtc != null &&
                    this.EndTimeUtc.Equals(input.EndTimeUtc))
                ) && 
                (
                    this.LinkFi == input.LinkFi ||
                    (this.LinkFi != null &&
                    this.LinkFi.Equals(input.LinkFi))
                ) && 
                (
                    this.LinkEn == input.LinkEn ||
                    (this.LinkEn != null &&
                    this.LinkEn.Equals(input.LinkEn))
                ) && 
                (
                    this.LinkTextFi == input.LinkTextFi ||
                    (this.LinkTextFi != null &&
                    this.LinkTextFi.Equals(input.LinkTextFi))
                ) && 
                (
                    this.LinkTextEn == input.LinkTextEn ||
                    (this.LinkTextEn != null &&
                    this.LinkTextEn.Equals(input.LinkTextEn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MessageFi != null)
                {
                    hashCode = (hashCode * 59) + this.MessageFi.GetHashCode();
                }
                if (this.MessageEn != null)
                {
                    hashCode = (hashCode * 59) + this.MessageEn.GetHashCode();
                }
                if (this.StartTimeUtc != null)
                {
                    hashCode = (hashCode * 59) + this.StartTimeUtc.GetHashCode();
                }
                if (this.EndTimeUtc != null)
                {
                    hashCode = (hashCode * 59) + this.EndTimeUtc.GetHashCode();
                }
                if (this.LinkFi != null)
                {
                    hashCode = (hashCode * 59) + this.LinkFi.GetHashCode();
                }
                if (this.LinkEn != null)
                {
                    hashCode = (hashCode * 59) + this.LinkEn.GetHashCode();
                }
                if (this.LinkTextFi != null)
                {
                    hashCode = (hashCode * 59) + this.LinkTextFi.GetHashCode();
                }
                if (this.LinkTextEn != null)
                {
                    hashCode = (hashCode * 59) + this.LinkTextEn.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
