/*
 * avoindata-api
 *
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingrid.Client.OpenAPIDateConverter;

namespace Fingrid.Model
{
    /// <summary>
    /// From T, pick a set of properties whose keys are in the union K
    /// </summary>
    [DataContract(Name = "Pick_TimeseriesDataPrivate.Exclude_keyofTimeseriesDataPrivate.datasetId__")]
    public partial class PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId : IEquatable<PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId" /> class.
        /// </summary>
        /// <param name="modifiedAtUtc">modifiedAtUtc.</param>
        /// <param name="startTime">startTime (required).</param>
        /// <param name="endTime">endTime (required).</param>
        /// <param name="value">value (required).</param>
        public PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId(DateTime modifiedAtUtc = default(DateTime), DateTime startTime = default(DateTime), DateTime endTime = default(DateTime), double value = default(double))
        {
            this.StartTime = startTime;
            this.EndTime = endTime;
            this.Value = value;
            this.ModifiedAtUtc = modifiedAtUtc;
        }

        /// <summary>
        /// Gets or Sets ModifiedAtUtc
        /// </summary>
        [DataMember(Name = "modifiedAtUtc", EmitDefaultValue = false)]
        public DateTime ModifiedAtUtc { get; set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [DataMember(Name = "startTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        [DataMember(Name = "endTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public double Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId {\n");
            sb.Append("  ModifiedAtUtc: ").Append(ModifiedAtUtc).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId);
        }

        /// <summary>
        /// Returns true if PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId instances are equal
        /// </summary>
        /// <param name="input">Instance of PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetId input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ModifiedAtUtc == input.ModifiedAtUtc ||
                    (this.ModifiedAtUtc != null &&
                    this.ModifiedAtUtc.Equals(input.ModifiedAtUtc))
                ) && 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.Value == input.Value ||
                    this.Value.Equals(input.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ModifiedAtUtc != null)
                {
                    hashCode = (hashCode * 59) + this.ModifiedAtUtc.GetHashCode();
                }
                if (this.StartTime != null)
                {
                    hashCode = (hashCode * 59) + this.StartTime.GetHashCode();
                }
                if (this.EndTime != null)
                {
                    hashCode = (hashCode * 59) + this.EndTime.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
