/*
 * avoindata-api
 *
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingrid.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Fingrid.Model
{
    /// <summary>
    /// TimeseriesDataResponse
    /// </summary>
    [JsonConverter(typeof(TimeseriesDataResponseJsonConverter))]
    [DataContract(Name = "TimeseriesDataResponse")]
    public partial class TimeseriesDataResponse : AbstractOpenAPISchema, IEquatable<TimeseriesDataResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeseriesDataResponse" /> class
        /// with the <see cref="IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod.</param>
        public TimeseriesDataResponse(IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TimeseriesDataResponse" /> class
        /// with the <see cref="TimeseriesDataCsvResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TimeseriesDataCsvResponse.</param>
        public TimeseriesDataResponse(TimeseriesDataCsvResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TimeseriesDataResponse" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public TimeseriesDataResponse(string actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TimeseriesDataCsvResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(string))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod, TimeseriesDataCsvResponse, string");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod`. If the actual instance is not `IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod</returns>
        public IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod GetIWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod()
        {
            return (IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TimeseriesDataCsvResponse`. If the actual instance is not `TimeseriesDataCsvResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TimeseriesDataCsvResponse</returns>
        public TimeseriesDataCsvResponse GetTimeseriesDataCsvResponse()
        {
            return (TimeseriesDataCsvResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `string`. If the actual instance is not `string`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TimeseriesDataResponse {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, TimeseriesDataResponse.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of TimeseriesDataResponse
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of TimeseriesDataResponse</returns>
        public static TimeseriesDataResponse FromJson(string jsonString)
        {
            TimeseriesDataResponse newTimeseriesDataResponse = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newTimeseriesDataResponse;
            }

            try
            {
                newTimeseriesDataResponse = new TimeseriesDataResponse(JsonConvert.DeserializeObject<IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod>(jsonString, TimeseriesDataResponse.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newTimeseriesDataResponse;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newTimeseriesDataResponse = new TimeseriesDataResponse(JsonConvert.DeserializeObject<TimeseriesDataCsvResponse>(jsonString, TimeseriesDataResponse.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newTimeseriesDataResponse;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TimeseriesDataCsvResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newTimeseriesDataResponse = new TimeseriesDataResponse(JsonConvert.DeserializeObject<string>(jsonString, TimeseriesDataResponse.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newTimeseriesDataResponse;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into string: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TimeseriesDataResponse);
        }

        /// <summary>
        /// Returns true if TimeseriesDataResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TimeseriesDataResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TimeseriesDataResponse input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for TimeseriesDataResponse
    /// </summary>
    public class TimeseriesDataResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(TimeseriesDataResponse).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return TimeseriesDataResponse.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
